### PR TITLE
React: Allow deletion of keys

### PR DESCRIPTION
**Pull request by salto-edit**

### CODE REVIEW

**Comment by ltworf** [comment]
Thanks @salto-edit! It was really needed. I'll be expecting the regexp patch next :P

**Comment by salto-edit** [comment]
Glad you liked it. Is the project mentoring GSoC students? I would be interested.

**Comment by ltworf** [comment]
I think the GSoC already started or will start very soon, so for this year the deadline has expired unfortunately.

**Comment by salto-edit** [comment]
Promise me to apply next year :smiley:

**Comment by salto-edit** [comment]
My nickname on github is salto-edit. Feel free to contact me anytime.

**Comment by ltworf** [comment]
Only if you fix your other pull request!

**Comment by salto-edit** [comment]
I did that. Check again.

**Pull request merged**
